### PR TITLE
Added test for async create protected

### PR DESCRIPTION
**Pull request by Randgalt**

### CODE REVIEW

**Comment by joshng** [comment]
Thanks, @Randgalt.  I think this specific test is actually missing the issue that I discovered, though: this would pass on master today without my fix, because the way it sets `doProtected` directly causes the protection code to be invoked -- just with `protectionId = null`. So the node's path is decorated with the `PROTECTION_PREFIX`, but the protection _token_ is `null` (eg, `/_c_null-yo`).

To cover the issue and prevent regressions, I think the test will need to assert that the generated token looks like a valid UUID, which is a little clumsy...

Also, I'll mention that I did consider writing a test for this, but discovered that the curator test suite is already failing due to some other issue (even in the CI environment: https://builds.apache.org/job/Curator/ -- `org.apache.curator.framework.imps.TestFrameworkEdges.testDeleteChildrenConcurrently`), so my motivation was deflated 😏 .

Anyway, I'll accept this PR, then take a stab at updating the test to assert more about the generated token, and we can go from there.

**Comment by Randgalt** [comment]
Hmm - the test failed for me when I commented out your change. But, then, I did it pretty fast and maybe missed something.

**Comment by Randgalt** [comment]
Our tests our flakey (especially on Apache's Jenkins). All tests pass for me though locally. Is `testDeleteChildrenConcurrently()` failing for you?

**Comment by joshng** [comment]
yes, it's failing for me:

```
Results :

Failed tests:
org.apache.curator.framework.imps.TestFrameworkEdges.testDeleteChildrenConcurrently(org.apache.curator.framework.imps.TestFrameworkEdges)
  Run 1: PASS
  Run 2: TestFrameworkEdges.testDeleteChildrenConcurrently:716 expected [true] but found [false]


Tests run: 190, Failures: 1, Errors: 0, Skipped: 0```

**Comment by joshng** [comment]
true, commenting out my added code would cause your test to fail -- but that's because my change also _deleted_ the line that was setting `this.doProtected = doProtected`.

**Comment by Randgalt** [comment]
doh

**Comment by Randgalt** [comment]
Do us a favor if you don't mind, change `Assert.assertTrue(countDownLatch.await(10, TimeUnit.SECONDS));` to `Assert.assertTrue(countDownLatch.await(60, TimeUnit.SECONDS));` and see if it works.

**Comment by joshng** [comment]
(giving that a try...)

**Comment by joshng** [comment]
ok, yeah, increasing the timeout was sufficient to get my overtaxed system to pass that test. (still waiting for the recipes tests to finish ... ... ...)

**Comment by Randgalt** [comment]
That's what I thought. It's a persistent problem with our tests. There's no way to get inside of ZK so our tests all assume timing. Newer tests use the `Timing` object which can be given a multiple from the command line but that one is really old.

**Comment by joshng** [comment]
yeah, I was just thinking about this problem... for this test, it seems to me, you don't necessarily need to "get inside of zk"; you just need a way to intercept the framework execution to have it pause in a specific state, so that you can change zk out from under it. I'm imagining introducing a no-op "instrumentation" hook somewhere (inside of `CuratorFrameworkImpl`, probably) that would be invoked with each operation before dispatching... That could then be swapped out for a test-specific strategies as needed to interleave with the internal flow.

Probably a big job to get it patched in, but I imagine this might speed up testing significantly, and improve confidence by ensuring that the intended patterns are being exercised.

**Comment by Randgalt** [comment]
The problem is most of our tests rely on the in-memory ZK server to do some work. The timing of that work cannot be predicted and taxed machine make it go very slowly. Ideally, we'd get some test harnesses inside ZK. I've added a few over the years, but much more could be done.

**Comment by joshng** [comment]
I see, yeah, you can't really put a bound on how long these things will take, because they depend on ZK to do some of the work. Regardless, I think that'd be less of a concern if you had more fine-grained control over the timing of the operations that are initiated in your client. This failing test, for example, is creating **5000** keys in ZK in an effort to ensure that the deletion process takes long enough for another thread to perturb the system concurrently. If you could pause the `deletingChildrenIfNecessary` loop in the middle, I think you could exercise the intended concurrency with just 2 children, right? If so, choosing the timeout wouldn't be such an issue.

Anyway, just offering ideas... My team is heavily active with such work, needing to explore the nooks and crannies of a complex distributed state-space to assert correct fault-tolerance behavior. Introducing explicit interception-points is essential to make that kind of testing feasible, because causing faults at the intended time is impossible otherwise. Seems similar to the focus here.

**Comment by Randgalt** [comment]
We have stuff like that in Curator (debugCountDownLatches, etc.). But, we'd love to have more! If you can think of anything we'd appreciate additional PRs. We're also pretty desperate for more committers if you're interested in that.

**Comment by joshng** [comment]
Heh... Ok, I appreciate the invitation; I'll see what I can cook up, but my time is limited, plate is full, yadda yadda... 🙂 

After a quick glance, I'm eyeballing `processBackgroundOperation` as the sort of collection-point I'd want to instrument... But I see that foreground operations don't appear to go through any such gate, just using `client.getZooKeeper` directly to do their business. So introducing an interceptor looks like it'd be a big job, as I feared.

**Pull request merged**
